fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin

job_search:
    resource: "@JobSearchBundle/Resources/config/routing.yml"
    prefix:   /ajax/jobsearch
    
app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /
