admin_api_job:
    resource: "@AdminBundle/Resources/config/routing/API/job.yml"
    prefix:   /api/job

admin_jmp_job:
    resource: "@AdminBundle/Resources/config/routing/JMP/job.yml"
    prefix:   /jmp/job
    
admin_jmp_business_unit:
    resource: "@AdminBundle/Resources/config/routing/JMP/businessunit.yml"
    prefix:   /jmp/businessunit    
    
admin_jmp_location:
    resource: "@AdminBundle/Resources/config/routing/JMP/location.yml"
    prefix:   /jmp/location    
    
admin_jmp_career_area:
    resource: "@AdminBundle/Resources/config/routing/JMP/careerarea.yml"
    prefix:   /jmp/careerarea     
    
admin_jmp_category:
    resource: "@AdminBundle/Resources/config/routing/JMP/category.yml"
    prefix:   /jmp/category

admin_jmp_job_type:
    resource: "@AdminBundle/Resources/config/routing/JMP/jobtype.yml"
    prefix:   /jmp/jobtype 
    
admin_jmp_job_status:
    resource: "@AdminBundle/Resources/config/routing/JMP/jobstatus.yml"
    prefix:   /jmp/jobstatus 
    
admin_jmp_salary_type:
    resource: "@AdminBundle/Resources/config/routing/JMP/salarytype.yml"
    prefix:   /jmp/salarytype 
    
admin_jmp_career_level:
    resource: "@AdminBundle/Resources/config/routing/JMP/careerlevel.yml"
    prefix:   /jmp/careerlevel 
    
admin_jmp_education_level:
    resource: "@AdminBundle/Resources/config/routing/JMP/educationlevel.yml"
    prefix:   /jmp/educationlevel    
    
admin_jmp_years_of_experience_level:
    resource: "@AdminBundle/Resources/config/routing/JMP/yearsofexperience.yml"
    prefix:   /jmp/yearsofexperience     
    
admin_homepage:
    path:     /
    defaults: { _controller: AdminBundle:Default:index }
    
admin_profile:
    path:     /profile
    defaults: { _controller: AdminBundle:Default:profile }
    
admin_settings:
    path:     /settings
    defaults: { _controller: AdminBundle:Default:settings } 
    
admin_users:
    path:     /users
    defaults: { _controller: AdminBundle:Default:users }
    
admin_jmp:
    path:     /jmp
    defaults: { _controller: AdminBundle:Default:jmp }    
    
admin_report:
    path:     /report
    defaults: { _controller: AdminBundle:Default:report }    
    
admin_analytics:
    path:     /analytics
    defaults: { _controller: AdminBundle:Default:analytics }
    
admin_workable:
    path:     /workable
    defaults: { _controller: AdminBundle:Workable:index }

admin_workable_search_jobs:
    path:     /workable/search/jobs
    defaults: { _controller: AdminBundle:Workable:searchJobs }
    
admin_workable_search_job:
    path:     /workable/job/{id}
    defaults: { _controller: AdminBundle:Workable:getJob }    

admin_workable_search_job_application_fields:
    path:     /workable/job/{id}/application_fields
    defaults: { _controller: AdminBundle:Workable:getJobApplicationFields }
    
admin_workable_search_candidates:
    path:     /workable/search/candidates
    defaults: { _controller: AdminBundle:Workable:searchCandidates }