admin_jmp_career_area_index:
    path:     /
    defaults: { _controller: "AdminBundle:JMP\\CareerArea:index" }
    methods:  GET

admin_jmp_career_area_edit:
    path:     /{id}/show
    defaults: { _controller: "AdminBundle:JMP\\CareerArea:edit" }
    methods:  GET

admin_jmp_career_area_new:
    path:     /new
    defaults: { _controller: "AdminBundle:JMP\\CareerArea:new" }
    methods:  [GET, POST]

admin_jmp_career_area_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdminBundle:JMP\\CareerArea:delete" }
    methods:  DELETE
