admin_jmp_education_level_index:
    path:     /
    defaults: { _controller: "AdminBundle:JMP\\EducationLevel:index" }
    methods:  GET

admin_jmp_education_level_edit:
    path:     /{id}/show
    defaults: { _controller: "AdminBundle:JMP\\EducationLevel:edit" }
    methods:  GET

admin_jmp_education_level_new:
    path:     /new
    defaults: { _controller: "AdminBundle:JMP\\EducationLevel:new" }
    methods:  [GET, POST]

admin_jmp_education_level_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdminBundle:JMP\\EducationLevel:delete" }
    methods:  DELETE
