app_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }
    
app_job_detail:
    path:     /job-details/{title}/{id}
    defaults: { _controller: AppBundle:Default:job }    