admin_job_index:
    path:     /
    defaults: { _controller: "AdminBundle:API\\Job:index" }
    methods:  GET

admin_job_show:
    path:     /{id}/show
    defaults: { _controller: "AdminBundle:API\\Job:show" }
    methods:  GET

admin_job_new:
    path:     /new
    defaults: { _controller: "AdminBundle:API\\Job:new" }
    methods:  [GET, POST]

admin_job_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdminBundle:API\\Job:edit" }
    methods:  [GET, POST]

admin_job_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdminBundle:API\\Job:delete" }
    methods:  DELETE
